services:
  cim-fastapi:
    container_name: cim-fastapi
    build: .
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["sh", "-c", "pip install --no-cache-dir -r requirements.txt && uvicorn login_server:app --host 0.0.0.0 --port 8000"]
  metrics-db:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - ./metrics_data:/data/db
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 5
  watcher:
    build: .
    command: ["python","watch_db_changes.py"]
    depends_on:
      - fastapi-app
      - metrics-db
      - postgres
    environment:
      - MONGO_URI=mongodb://metrics-db:27017/?replicaSet=rs0
      - METRICS_DB_NAME=metricsdb
      - METRICS_COLLECTION=metrics
      - PG_DSN=postgresql://postgres:postgres@postgres:5432/postgres
      - PROCESSOR_NAME=kv_exporter
