services:
  cim-fastapi:
    build: .
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["sh", "-c", "pip install --no-cache-dir -r requirements.txt && uvicorn login_server:app --host 0.0.0.0 --port 8000"]
  metrics-db:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - ./metrics_data:/data/db
    ports:
      - "27017:27017"